### ISSUE TITLE
ERROR:  Could not find a valid gem 'jaxb2ruby' (>= 0) in any repository

### ISSUE THREAD

**Issue by edward-ellis** [sshaw/jaxb2ruby#4]
From which repository can I install your gem?  It isn't in rubygems.org.

**Comment by sshaw** [comment]
[Done](https://rubygems.org/gems/jaxb2ruby).

I never make a release because there was more I wanted to add and some subtle issues. But hey, it's a v0.0.1 release. 

Note that you'll have to run it on a JRuby version < 9.0.
